### ISSUE TITLE
Blame cannot be disabled

### ISSUE THREAD

**Issue by maciejmiklas** [zielu/GitToolBox#586] opened 2024-12-16 14:44 UTC
**Describe the bug**
I see inline blame, but it's disabled

**To Reproduce**
<img width="677" alt="image" src="https://github.com/user-attachments/assets/39d0cf07-d6bf-4ae8-885d-7e4af528f256" />

**Expected behavior**
blame should not be visible

**Plugin version**
600.0.10+243

**IDE version**
2024.3.1

**Screenshots**
<img width="491" alt="image" src="https://github.com/user-attachments/assets/a6fc5e34-df8a-4673-8986-ee427d6cffe7" />

**Comment by zielu** [comment] 2024-12-16 15:15
Duplicate of #585

**Comment by zielu** [comment] 2024-12-16 19:30
Please try, 600.0.11+243

**Closed as completed** 2024-12-16 21:01 UTC
Labels: bug

**Comment by maciejmiklas** [comment] 2024-12-19 13:33
Thank you - that was super fast!
