### ISSUE TITLE
Disable Override Commit Message Validation Per Project

### ISSUE THREAD

**Issue by PanjiNamjaElf** [zielu/GitToolBox#358] opened 2021-11-16 01:07 UTC
Hi... I have disable the override checkbox on Commit -> Message Validation
But when I want to commit change the validation become checked again so it make invalid message validation

It is a bug or any something I missing ?

1. Uncheck the override checkbox
![image](https://user-images.githubusercontent.com/16651293/141877175-7f1947e9-303e-4336-ba58-681a6d4cbeab.png)

2. When commit dialog show
![image](https://user-images.githubusercontent.com/16651293/141877618-d2bd450f-1788-4ef2-8335-adebe1e72e46.png)

3. After close the commit dialog and open Settings > GitToolBox > GitToolBox Project > Commit > Message Validation
The override become checked again
![image](https://user-images.githubusercontent.com/16651293/141877724-8a9a7cbb-b11c-4f67-b583-7510b4396d5f.png)

**Comment by zielu** [comment] 2021-11-16 02:16
Hi, it works like this - if you want to disable something per-project you need to check Override and then disable given setting. The moment you uncheck Override it shows current value from application level.

Checkboxes in commit dialog Before Commit take current value from either project or application level (depending on state of Override) but the moment they are modified they create implicit project level override - so that unchecking something in Commit Dialog won't modify application level setting hence impacting all projects without override.

Like this in your case:
<img width="733" alt="image" src="https://user-images.githubusercontent.com/464103/141883274-be23fe21-976a-4f54-badf-6fcc8ef54f5a.png">

**Comment by PanjiNamjaElf** [comment] 2021-11-16 02:42
On my application commit regex pattern using like this `(?:fix|chore|docs|feat|refactor|perf|ci|style|test)(?:\(.*\))?: [a-z].*(\s#\d+)?`
So I must override it on project settings to using same regex pattern like application settings?

Ok.. thank's ☺️

**Comment by zielu** [comment] 2021-11-16 15:45
@PanjiNamjaElf out of curiosity - would it be more logical for you that whenever you enable override initial values in UI are copied from app-level ?

I'm wondering whether current implementation is too confusing.

**Comment by PanjiNamjaElf** [comment] 2021-11-17 00:30
I think it will be easier understand if we enable override button it will use setting from project and copy initial value from app-level but if not checked it will use application settings.. but now it must checked and copy value from app level settings if want use same settings.. is not practice😅

**Comment by jpvantelon** [comment] 2021-12-13 13:55
Hi @zielu. I had the same problem as @PanjiNamjaElf.
The problem was really that, in the `GitToolBox Project` configuration, on the `Commit` tab, if you unchecked the override checkboxes for `Message Validation`, they were kind of automatically rechecked in the background !
So even if you didn't wanted to override these settings, you kind of had to :sweat_smile: !

But with the latest version (212.8.4), the problem seems to be fixed.

Now, if I uncheck the override checkboxes, they stay unchecked.

From the changelog, it seems to be a side effect, but thanks anyway @zielu :+1:  !

**Comment by jpvantelon** [comment] 2021-12-14 14:37
Well... In fact the bug is still here :confused:. I restarted PHPStorm, maybe that was just that, and yesterday I didn't actually performed a commit, so maybe I dreamt about the fix, or maybe it was just monday :smile:.

So today, I tried to commit and got an error about the commit message not being correct.
I checked in the `GitToolBox Project` configuration, on the `Commit` tab, and the override checkboxes were checked again :frowning: ...
So had to copy past settings from app-level, and was able to commit.

So still something funky going on with these override checkboxes...

**Comment by zielu** [comment] 2021-12-14 17:56
Heh, the logic of those specific checkboxes is more funky than it should be...
I mean - there are sources of changes:
- Settings etc..
- commit dialog
the issue is with second one - what is the expectation of user what should happen ?

If there is existing project override logic is simple - just modify override value. But assuming there is no override - should changing setting in commit dialog change global setting ? This looked to me as source of confusion - you disable in commit dialog and you could disable commit validation for all projects - imho this is an unexpected side-effect. To avoid this the moment a change is made in commit dialog an implicit override is created.

I see one potential gap with current approach - override is created and commit dialog selection applied - what I noticed is missing is copying of validation pattern. This can be fixed but one more issue is possible - the moment implicit override is created, validation pattern gets detached from app level config so:

1. user enables validation in commit dialog
2. override is created + app level pattern copied
3. user does not know about new override and expects app-level pattern to be in effect
4. user updates app-level pattern
5. project-level pattern does not reflect this

To make it manageable it looks like validation option  and pattern should have separate overrides. This way there should not be any unexpected side-effects

**Comment by zielu** [comment] 2022-02-22 10:55
Released to EAP channel in variant.8.7

**Closed** 2022-03-04 09:22 UTC
Labels: enhancement, 203, 212
