### ISSUE TITLE
Error state

### ISSUE THREAD

**Issue by YiiGuxing** [zielu/GitToolBox#26] opened 2016-11-18 03:30 UTC
![1](https://cloud.githubusercontent.com/assets/10737066/20417657/e1a937b2-ad81-11e6-882e-4564d8c965ec.png)

**Comment by peteyan** [comment] 2016-11-18 11:14
I'm the same problem too. The up arrow has also display when it pushed.

**Comment by zielu** [comment] 2016-11-18 17:32
Duplicate of #25 - I'm already working on fix

**Closed by zielu** 2016-11-18 17:32 UTC
Labels: duplicate

**Comment by zielu** [comment] 2016-11-18 18:26
Attempted fix in 16.3.4
