### ISSUE TITLE
[BUG] After upgrading PyCharm to 2024.3.1, inline git blame cannot be hidden

### ISSUE THREAD

**Issue by illagrenan** [zielu/GitToolBox#585] opened 2024-12-16 09:25 UTC
**Describe the bug**

After upgrading PyCharm to 2024.3.1, I still see inline git blame, even though I have it disabled in the settings. 

**Expected behavior**

When inline blame is turned off, it should not be displayed.

**Plugin version**

`600.0.10+243`

**IDE version**

```
PyCharm 2024.3.1 (Professional Edition)
Build #PY-243.22562.180, built on December 11, 2024
Licensed to Vaclav Dohnal
Subscription is active until March 30, 2025.
Runtime version: 21.0.5+8-b631.28 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 9216M
Cores: 16
Registry:
  ide.experimental.ui=true
  i18n.locale=
  editor.minimap.enabled=true
Non-Bundled Plugins:
  com.jetbrains.gerryThemesPro (2024.1.1206)
  org.intellij.plugins.hcl (243.22562.13)
  com.nasller.CodeGlancePro (1.9.4)
  lermitage.ij.all.pack (2024.12.2)
  com.mroche.JsonHelper (1.3.2)
  dev.turingcomplete.intellijdevelopertoolsplugins (6.0.1)
  com.intellij.ideolog (243.22562.180)
  name.kropp.intellij.makefile (243.21565.122)
  String Manipulation (9.15.0)
  krasa.CpuUsageIndicator (1.18.0-IJ2023)
  Key Promoter X (2024.2.2)
  com.intellij.plugin.adernov.powershell (2.8.0)
  AceJump (3.8.19)
  com.github.camork.fileExpander (2.5)
  org.mvnsearch.plugins.justPlugin (0.6.8)
  com.intellij.kubernetes (243.22562.112)
  com.intellij.ml.llm (243.22562.251.6)
  com.koxudaxi.ruff (0.0.42)
  ru.adelf.idea.dotenv (2024.3)
  com.koxudaxi.pydantic (0.4.16)
  com.intellij.grazie.pro (0.3.351)
  PlantUML integration (7.11.2-IJ2023.2)
  org.asciidoctor.intellij.asciidoc (0.43.3)
  com.intellij.bigdatatools.core (243.22562.145)
  com.intellij.bigdatatools.kafka (243.22562.145)
  com.intellij.bigdatatools.binary.files (243.21565.129)
  com.intellij.bigdatatools.databricks (243.21565.129)
  com.intellij.bigdatatools.rfs (243.22562.145)
  com.intellij.bigdatatools.metastore.core (243.21565.129)
  com.intellij.bigdatatools.flink (243.21565.129)
  com.github.jk1.ytplugin (2024.2.123)
  gr.jchrist.gitextender (0.8.2)
  uk.co.ben-gibson.remote.repository.mapper (4.5.2)
  zielu.gitworktree (1.0.10+231)
  mobi.hsz.idea.gitignore (4.5.4)
  izhangzhihao.rainbow.brackets (2024.2.8-241)
  pro.bashsupport (4.5.0.243)
  zielu.gittoolbox (600.0.10+243)
  com.intellij.bigdatatools.spark (243.22562.145)
  com.intellij.bigdatatools.zeppelin (243.22562.13)
  com.intellij.bigdatatools (243.21565.129)
```

**Screenshots**

![image](https://github.com/user-attachments/assets/c61933e1-f81b-41e6-8747-1277ae8c1062)
![image](https://github.com/user-attachments/assets/7df26688-1d39-4889-91cb-a51347c015db)

**Comment by hogejo** [comment] 2024-12-16 10:17
I have a similar issue, in the free version, where in IntelliJ IDEA, the blame is always shown at a fresh IDE start (or project open in new window).

I can hide them again:
* Enable inline blame
* apply
* Disable inline blame
* apply

Can this be related to recent #342 ?

**Comment by zielu** [comment] 2024-12-16 10:19
I'll look into it today evening

**Comment by 0x6d6c** [comment] 2024-12-16 13:58
The workaround posted by @hogejo works for me, but only partially. E.g. On the left there is an XML file with no inline blames, on the right – a PHP file and the inline blames are visible (despite being disabled in the plugin settings).
![image](https://github.com/user-attachments/assets/093b5f0f-65e2-45b4-ba76-51067bd532ff)

**Comment by zielu** [comment] 2024-12-16 14:46
I did noy check yet, but have a pretty good idea what is the root cause.

**Comment by zielu** [comment] 2024-12-16 17:03
When project is opened the setting is respected to restored opened files. When a new file is opened setting is not respected

**Comment by zielu** [comment] 2024-12-16 19:30
Please try, 600.0.11+243

**Comment by 0x6d6c** [comment] 2024-12-16 20:59
@zielu The issue seem to be fixed now. Dzięki!

**Closed as completed** 2024-12-16 21:01 UTC
Labels: bug

**Comment by LionGod8** [comment] 2024-12-17 11:49
Thanks for the quick fix, that was annoying ✌️
